services:
  - type: web
    name: hb-party
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_TEMP_TOKEN
        sync: false
